title = "Deploy a dependable system - Vault"
institution = "Vietnam National University - Ho Chi Minh City University of Technology"
semester = 242
major = "Computer Science"
faculty = "Computer Science and Engineer"

[course]
name = "Advanced software engineering Assignment"

[[teachers]] 
name = "Lê Đình Thuận" 

[[students]]
name = "Trần Nguyễn Phương Thành"
id = "2110541"

[[students]]
name = "Đỗ Nguyễn An Huy"
id = 2110193

[[students]]
name = "Tôn Trọng Tín"
id = "2033338"

[[students]]
name = "Nguyễn Sỹ Công"
id = 2210409

[[students]]
name = "Trần Quốc Toàn"
id = 2213540

[[students]]
name = "Huỳnh Tấn Sỹ"
id = 2112205

[[students]]
name = "Võ Nguyễn Gia Huy"
id = 2252270

[fonts]
serif = "Times New Roman"
monospace = "JetBrains Mono"
