= Demonstration

This section demonstrate our results for proof of work.

The 3 vaults are auto-unsealed, here are the logs and the screenshots:
- `vault-1`: Accessed on port 8081 of the Docker swarm master.
  - Logs:
    ```sh
fetch http://nl.alpinelinux.org/alpine/v3.19/main/x86_64/APKINDEX.tar.gz
WARNING: updating http://nl.alpinelinux.org/alpine/v3.19/main: temporary error (try again later)
fetch http://nl.alpinelinux.org/alpine/v3.19/community/x86_64/APKINDEX.tar.gz
WARNING: updating http://nl.alpinelinux.org/alpine/v3.19/community: temporary error (try again later)
OK: 14 MiB in 35 packages
vault-transit not ready yet, waiting...
vault-transit not ready yet, waiting...
vault-transit not ready yet, waiting...
vault-transit not ready yet, waiting...
vault-transit not ready yet, waiting...
vault-transit not ready yet, waiting...
vault-transit not ready yet, waiting...
vault-transit not ready yet, waiting...
vault-transit not ready yet, waiting...
vault-transit not ready yet, waiting...
vault-transit not ready yet, waiting...
vault-transit not ready yet, waiting...
vault-transit not ready yet, waiting...
vault-transit not ready yet, waiting...
vault-transit not ready yet, waiting...
vault-transit not ready yet, waiting...
Authenticating to Vault...
Authentication attempt  failed. Elapsed time: 0s of 300s
Retrying in 5 seconds...
Authentication successful!
Proceeding with Vault token...
Transit token retrieved successfully
Starting vault...
Waiting for Vault to start...
Initializing vault...
WARNING! The VAULT_TOKEN environment variable is set! The value of this
variable will take precedence; if this is unwanted please unset VAULT_TOKEN or
update its value accordingly.
Success! You are now authenticated. The token information displayed below
is already stored in the token helper. You do NOT need to run "vault login"

again. Future Vault requests will automatically use this token.

Key                  Value
---                  -----
token                hvs.vK3Q6zA07SL7gsc47GVSECEz
token_accessor       oVmzlZtwRanZO1VbKq4P7qAs
token_duration       ∞
token_renewable      false
token_policies       ["root"]
identity_policies    []
policies             ["root"]
Success! Enabled userpass auth method at: userpass/
Success! Uploaded policy: admin
Success! Data written to: auth/userpass/users/root
Success! Enabled the kv-v2 secrets engine at: kv/
    ```
  - Screenshots:
- `vault-2`: Accessed on port 8082 of the Docker swarm master.
  - Logs:
```sh
fetch http://nl.alpinelinux.org/alpine/v3.19/main/x86_64/APKINDEX.tar.gz
WARNING: updating http://nl.alpinelinux.org/alpine/v3.19/main: temporary error (try again later)
fetch http://nl.alpinelinux.org/alpine/v3.19/community/x86_64/APKINDEX.tar.gz
WARNING: updating http://nl.alpinelinux.org/alpine/v3.19/community: temporary error (try again later)
OK: 14 MiB in 35 packages
vault-transit not ready yet, waiting...
vault-transit not ready yet, waiting...
vault-transit not ready yet, waiting...
vault-transit not ready yet, waiting...
vault-transit not ready yet, waiting...
vault-transit not ready yet, waiting...
vault-transit not ready yet, waiting...
vault-transit not ready yet, waiting...
vault-transit not ready yet, waiting...
vault-transit not ready yet, waiting...
vault-transit not ready yet, waiting...
vault-transit not ready yet, waiting...
vault-transit not ready yet, waiting...
vault-transit not ready yet, waiting...
vault-transit not ready yet, waiting...
vault-transit not ready yet, waiting...
vault-transit not ready yet, waiting...
Primary vault still sealed, waiting...
Primary vault still sealed, waiting...
Primary vault still sealed, waiting...
Primary vault still sealed, waiting...
Primary vault still sealed, waiting...
Primary vault still sealed, waiting...
Primary vault still sealed, waiting...
Primary vault still sealed, waiting...
Primary vault still sealed, waiting...
Primary vault still sealed, waiting...
Primary vault still sealed, waiting...
Primary vault still sealed, waiting...
Primary vault still sealed, waiting...
Primary vault still sealed, waiting...
Primary vault still sealed, waiting...
Primary vault still sealed, waiting...
Primary vault still sealed, waiting...
Primary vault still sealed, waiting...
Primary vault still sealed, waiting...
Primary vault still sealed, waiting...
Authenticating to Vault...
Authentication successful!
Proceeding with Vault token...
Transit token retrieved successfully
Starting vault...
Key       Value
---       -----
Joined    true
```
  - Screenshots:
- `vault-3`: Accessed on port 8083 of the Docker swarm master.
  - Logs:
```sh
fetch http://nl.alpinelinux.org/alpine/v3.19/main/x86_64/APKINDEX.tar.gz
WARNING: updating http://nl.alpinelinux.org/alpine/v3.19/main: temporary error (try again later)
fetch http://nl.alpinelinux.org/alpine/v3.19/community/x86_64/APKINDEX.tar.gz
WARNING: updating http://nl.alpinelinux.org/alpine/v3.19/community: temporary error (try again later)
OK: 14 MiB in 35 packages
vault-transit not ready yet, waiting...
vault-transit not ready yet, waiting...
vault-transit not ready yet, waiting...
vault-transit not ready yet, waiting...
vault-transit not ready yet, waiting...
vault-transit not ready yet, waiting...
vault-transit not ready yet, waiting...
vault-transit not ready yet, waiting...
vault-transit not ready yet, waiting...
vault-transit not ready yet, waiting...
vault-transit not ready yet, waiting...
vault-transit not ready yet, waiting...
vault-transit not ready yet, waiting...
vault-transit not ready yet, waiting...
vault-transit not ready yet, waiting...
vault-transit not ready yet, waiting...
Primary vault still sealed, waiting...
Primary vault still sealed, waiting...
Primary vault still sealed, waiting...
Primary vault still sealed, waiting...
Primary vault still sealed, waiting...
Primary vault still sealed, waiting...
Primary vault still sealed, waiting...
Primary vault still sealed, waiting...
Primary vault still sealed, waiting...
Primary vault still sealed, waiting...
Primary vault still sealed, waiting...
Primary vault still sealed, waiting...
Primary vault still sealed, waiting...
Primary vault still sealed, waiting...
Primary vault still sealed, waiting...
Primary vault still sealed, waiting...
Primary vault still sealed, waiting...
Primary vault still sealed, waiting...
Primary vault still sealed, waiting...
Primary vault still sealed, waiting...
Authenticating to Vault...
Authentication successful!
Proceeding with Vault token...
Transit token retrieved successfully
Starting vault...
Key       Value
---       -----
Joined    true
```
  - Screenshots:
