secrets:
  transit_token:
    external: true

services:
  vault-transit-1:
    container_name: vault-transit-1
    build:
      context: ./vault-transit-1
      dockerfile: ./Dockerfile
    hostname: vault-transit-1
    ports:
      - "8200:8200"
    restart: always
    volumes:
      - vault-transit-1-data:/vault/data
    cap_add:
      - IPC_LOCK
    networks:
      - vault-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8200/v1/sys/health"]
      interval: 5s
      timeout: 3s
      retries: 10

  vault-1:
    container_name: vault-1
    build:
      context: ./vault-1
      dockerfile: ./Dockerfile
    hostname: vault-1
    ports:
      - "8201:8200"
    restart: always
    cap_add:
      - IPC_LOCK
    secrets:
      - transit_token
    volumes:
      - vault-1-data:/vault/data
    depends_on:
      - vault-transit-1
    networks:
      - vault-network

networks:
  vault-network:
    driver: overlay
    attachable: true

volumes:
  vault-transit-1-data:
  vault-1-data:
