services:
  vault-transit-1:
    image: vault-transit-1
    hostname: vault-transit-1
    ports:
      - "8200:8200"
    volumes:
      - vault-transit-1-data:/vault/data
    cap_add:
      - IPC_LOCK
    networks:
      - vault-network
    deploy:
      mode: replicated
      replicas: 1

  vault-1:
    image: vault-1
    hostname: vault-1
    ports:
      - "8201:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - vault-1-data:/vault/data
    networks:
      - vault-network
    deploy:
      mode: replicated
      replicas: 1

  vault-2:
    image: vault-2
    hostname: vault-2
    ports:
      - "8202:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - vault-2-data:/vault/data
    networks:
      - vault-network
    deploy:
      mode: replicated
      replicas: 1

networks:
  vault-network:
    driver: overlay
    attachable: true

volumes:
  vault-transit-1-data:
  vault-1-data:
  vault-2-data:
