global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'vault-1'
    metrics_path: '/v1/sys/metrics'
    params:
      format: ['prometheus']
    static_configs:
      - targets: ['vault-1:8200']
    bearer_token: ${METRICS_TOKEN}

  - job_name: 'vault-2'
    metrics_path: '/v1/sys/metrics'
    params:
      format: ['prometheus']
    static_configs:
      - targets: ['vault-2:8200']
    bearer_token: ${METRICS_TOKEN}

  - job_name: 'vault-3'
    metrics_path: '/v1/sys/metrics'
    params:
      format: ['prometheus']
    static_configs:
      - targets: ['vault-3:8200']
    bearer_token: ${METRICS_TOKEN}
